### PR TITLE
CI agains jruby-9.1.9.0

### PR DESCRIPTION
**Pull request by yahonda**
http://jruby.org/2017/05/16/jruby-9-1-9-0.html

There is `NoMethodError: undefined method `status' for #<Array:0x47c4ecdc>` error reported at CI with jruby-head. This error may reproduce with Ruby 9.1.9.0.

### CODE REVIEW

**Comment by PragTob** [comment]
Thank you for this and GRML... gotta have a look at JRuby to see what's up :)

**Comment by PragTob** [comment]
referencing jruby/jruby#4610 :)

**Comment by PragTob** [comment]
aka it's a JRuby regression :|

**Comment by PragTob** [comment]
new simplecov-html version released, rerunning the build, should pick up the new version and fix it

**Comment by yahonda** [comment]
Thanks for releasing new simpleconv-html. simplecov is working fine with Ruby 9.1.9.0.
