### ISSUE TITLE
Simplecov refers to an undefined method when 'json-schema' is loaded and 'json' is not loaded.

### ISSUE THREAD

**Issue by punkle** [colszowka/simplecov#366]
Simplecov refers to an undefined method when 'json-schema' is loaded and 'json' is not loaded.

    /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/simplecov-0.8.2/lib/simplecov/json.rb:16:in `dump': undefined method `pretty_generate' for JSON:Module (NoMethodError)
	    from /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/simplecov-0.8.2/lib/simplecov/result_merger.rb:74:in `block in store_result'
	    from /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/simplecov-0.8.2/lib/simplecov/result_merger.rb:72:in `open'
	    from /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/simplecov-0.8.2/lib/simplecov/result_merger.rb:72:in `store_result'
	    from /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/simplecov-0.8.2/lib/simplecov.rb:48:in `result'
	    from /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/simplecov-0.8.2/lib/simplecov/configuration.rb:139:in `block in at_exit'

**Comment by colszowka** [comment]
@punkle Could you please upgrade to the latest 0.9.1 version and verify you see the same problem?

**Comment by bf4** [comment]
`JSON.pretty_generate` is part of the standard library.  If another gem you are using breaks that, I think the bug report should be there, no?

**Comment by punkle** [comment]
@colszowka apologies, it works fine in 0.9.1. @bf4 the json-schema gem uses the same JSON namespace as the standard library. It's possible to define resources in any namespace. I dont know of any agreement / pattern whereby this should / should not be done. Have you any insight on this?
